# Determines whether debug logs should be displayed in the console.
# Could also be used for other behaviour.
debug: false

# Database connection details, should you want to have a database connection.
# KEEP THIS COMMENTED OUT IN THIS DEFAULT CONFIG OTHERWISE SOME CONFIG PARSING WILL CAUSE ISSUES!
# Remember also to change the plugin value to match your plugin name. Do NOT change the ==: value.
#database:
#  ==: vg.civcraft.mc.civmodcore.dao.ManagedDatasource
#  plugin: Template
#  user: username
#  password: password
#  host: localhost
#  port: 3306
#  database: minecraft
#  poolsize: 5
#  connection_timeout: 10000
#  idle_timeout: 600000
#  max_lifetime: 7200000
